fs = require("fs")
fs.writeFileSync("H.txt","HELLO WORLD")
data=fs.readFileSync("H.txt")
console.log(data.toString())
//fs.mkdirSync("Hello")
fs.writeFileSync("HEllo/User.txt","CRUD")
fs.appendFileSync("HEllo/User.txt","\n Operation")
var data=fs.readFileSync("HEllo/User.txt","UTF-8")
fs.renameSync("HEllo/User.txt","HEllo/User1.txt")
console.log(data)
fs.unlinkSync("HEllo/User1.txt")
fs.rmdirSync("HEllo")
